depth = -11000;
menuon = true;
al = 0; //Alpha Var
cur_select = 0; //The selection Var.
inputstring = "";
inputtext[0] = 0; //Input Text X
inputtext[1] = 12; //Input Text X Max
inputtext[2] = 0; //Input Text Y
inputtext[3] = 3; //Input Text X Max
